# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/ohm/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ohm)

$(call add-radio-file-sha1-checked,radio/bootloader.img,2bccbd2f38f15c13eb7d5a89fd9d85f595e23bc3)

endif
