# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/ohm/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/ohm

PRODUCT_COPY_FILES += \
    vendor/amlogic/ohm/proprietary/odm/etc/a2dp_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/a2dp_audio_policy_configuration.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_configuration.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_volumes.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_ODM)/etc/default_volume_tables.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/firmware/firmware.le:$(TARGET_COPY_OUT_ODM)/etc/firmware/firmware.le \
    vendor/amlogic/ohm/proprietary/odm/etc/hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/hearing_aid_audio_policy_configuration.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/media_codecs.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_performance.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/ms12/libdolbyms12.so:$(TARGET_COPY_OUT_ODM)/etc/ms12/libdolbyms12.so \
    vendor/amlogic/ohm/proprietary/odm/etc/msd_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/msd_audio_policy_configuration.xml \
    vendor/amlogic/ohm/proprietary/odm/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/usb_audio_policy_configuration.xml \
    vendor/amlogic/ohm/proprietary/odm/lib/libHwAudio_dcvdec.so:$(TARGET_COPY_OUT_ODM)/lib/libHwAudio_dcvdec.so \
    vendor/amlogic/ohm/proprietary/odm/lib/libHwAudio_dtshd.so:$(TARGET_COPY_OUT_ODM)/lib/libHwAudio_dtshd.so \
    vendor/amlogic/ohm/proprietary/odm/ueventd.rc:$(TARGET_COPY_OUT_ODM)/ueventd.rc \
    vendor/amlogic/ohm/proprietary/system_ext/etc/permissions/com.droidlogic.tv.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.droidlogic.tv.settings.xml \
    vendor/amlogic/ohm/proprietary/system_ext/etc/permissions/droidlogic_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/droidlogic_permissions.xml \
    vendor/amlogic/ohm/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/2c1a33c0-44cc-11e5-bc3b-0002a5d5c51b.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/2c1a33c0-44cc-11e5-bc3b-0002a5d5c51b.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/526fc4fc-7ee6-4a12-96e3-83da9565bce8.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/526fc4fc-7ee6-4a12-96e3-83da9565bce8.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/8efb1e1c-37e5-4326-a5d6-8c33726c7d57.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/8efb1e1c-37e5-4326-a5d6-8c33726c7d57.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/9a04f079-9840-4286-ab92-e65be0885f95.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/9a04f079-9840-4286-ab92-e65be0885f95.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/e92a43ab-b4c8-4450-aa12-b1516259613b.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/e92a43ab-b4c8-4450-aa12-b1516259613b.ta \
    vendor/amlogic/ohm/proprietary/vendor/lib/teetz/ff2a4bea-ef6d-11e6-89cc-d4ae52a7b3b3.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/ff2a4bea-ef6d-11e6-89cc-d4ae52a7b3b3.ta

PRODUCT_PACKAGES += \
    DroidTvSettingsTwoPanel \
    droidlogic-hybrid-res
